FROM node:lts-buster

# Clone the bot repo
RUN git clone https://github.com/Awais-star-a11y/AWAIS-MD-v3 /app

# Set working directory
WORKDIR /app

# Install dependencies
RUN npm install

# Optional: install pm2 if your start script uses it
# RUN npm install -g pm2

# Expose port (Heroku will ignore this but good practice)
EXPOSE 8080

# Start the bot
CMD ["npm", "start"]
