FROM node:14
RUN git clone https://github.com/Awais-star-a11y/AWAIS-MD-v3 /root/xIKRATOSx
WORKDIR /root/xIKRATOSx
RUN npm install npm@latest || yarn install --network-concurrency 1
COPY . .
EXPOSE 9090
CMD ["npm", "start"]